config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  get "/index", to: "tasks#index"
  get "/index/:id", to: "tasks#show", as: :task

  get "/tasks/new", to: "tasks#new"   # gets the form
  post "/tasks", to: "tasks#create" # post (creating id)

  # Update (two HTTP Requests)
  get "/index/:id/edit", to: "tasks#edit", as: :edit # gets filled in form
  patch "/index/:id", to: "tasks#update" #saves it

  # Delete
  delete "/index/:id", to: "tasks#destroy", as: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to task_path(@task)
    else
      render :new
    end
  end

  def update
    set_task
    @task.update(task_params)
    @task.save
    redirect_to task_path(@task.id)
  end

  def destroy
    set_task
    @task.destroy
    redirect_to index_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.label :Done %>
  <%= f.check_box :completed %>

  <%= f.submit id: 'submit'%>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit Your Task</h1>
<%= render 'form', task: @task %>

<%= link_to 'Go Back', task_path(@task), class: 'button' %>

app/views/tasks/index.html.erb
<% open_tasks_count = @tasks.reject { |task| task.completed }.count %>
<h1>My Tasks</h1>
<h2> (Open Tasks: <%= open_tasks_count %>)</h2>


<% @tasks.each do |task| %>
  <ul>
    <li>
      <%= link_to task.title, task_path(task) %>
      <% if task.completed %>
        <span class="task-completed">&#10003;</span> <!-- Tick mark for completed tasks -->
      <% else %>
        <span class="task-not-completed">&#10007;</span> <!-- Cross mark for incomplete tasks -->
      <% end %>
    </li>
  </ul>
<% end %>

<%= link_to 'Add New Task', tasks_new_path, class: 'button' %>

app/views/tasks/new.html.erb
<h1>Add your new task</h1>
<%= render "tasks/form", task: @task %>

<%= link_to 'Go Back', index_path, class: 'button' %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

<ul>
  <li><%= @task.details %></li>
  <li>Completed: <%= @task.completed ? '✓' : '✗' %></li>
</ul>


<%= link_to 'Go Back', index_path, class: 'button' %>
<%= link_to 'Edit', edit_path(@task), class: 'button' %>
<%= link_to 'Delete', destroy_path(@task), data: {turbo_method: :delete, turbo_confirm: "Are you sure? Please confirm to delete."}, class: 'button' %>